config/routes.rb
Rails.application.routes.draw do
  resources :feeds
  resources :comments
  resources :posts do
    member do
      put "like" => "posts#upvote"
      put "unlike" => "posts#downvote"
    end
  end

  root to: "home#index"
  get 'home/index', as: 'user_root'

  devise_for :users, :controllers => { registrations: 'registrations' }

  get '/posts/hashtag/:name', to:'posts#hashtags'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord

    has_one_attached :image
    belongs_to :user, foreign_key: 'user_id'
    has_and_belongs_to_many :tags

    acts_as_votable

    after_create do
        post = Post.find_by(id: self.id)
        hashtags = self.body.scan(/#\w+/)
        hashtags.uniq.map do |hashtag|
            tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
            post.tags << tag
        end
    end

    before_update do
        post = Post.find_by(id: self.id)
        post.tags.clear
        hashtags = self.body.scan(/#\w+/)
        hashtags.uniq.map do |hashtag|
            tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
            post.tags << tag
        end
    end
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy, foreign_key: 'user_id'

  acts_as_voter

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [ :login ]

  attr_writer :login

  def login
    @login || self.phone || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(phone) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:phone].nil?
        where(conditions).first
      else
        where(phone: conditions[:phone]).first
      end
    end
  end

  validates_format_of :phone, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  # validate :validate_phone

  # def validate_phone
  #   if User.where(phone: phone).exists?
  #     errors.add(:phone, :invalid)
  #   end
  # end

  # validate :validate_email

  # def validate_email
  #   if User.where(email: email).exists?
  #     errors.add(:email, :invalid)
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:phone, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: [:login, :password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:post_id, :body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def
    index
    end
end

app/controllers/makepost_controller.rb
class MakepostController < ApplicationController
    before_action :authenticate_user!
    def index
        # do something
      end
    
      def show
        # do something
      end
    
      def create
        # do something
      end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy, :upvote, :downvote ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  #GET /posts/hashtag
  def hashtags
    tag = Tag.find_by(name: params[:name])
    @posts = tag.posts
  end

  #upvote_from user
  def upvote
    @post = Post.find(params[:id])
    @post.upvote_from current_user
    redirect_to posts_path
  end
  #downvote_from user
  def downvote
    @post = Post.find(params[:id])
    @post.downvote_from current_user
    redirect_to posts_path
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  #TODO: Feed of all users' posts
  def feed
    @posts = Post.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :image)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone, :password, :password_confirmation, :current_password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/makepost_helper.rb
module MakepostHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def render_with_hashtags(body)
        body.gsub(/#\w+/){|word| link_to word, "/posts/hashtag/#{word.delete('#')}"}.html_safe
    end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
    <%= button_to 'Sign out', destroy_user_session_path, :method => :delete %>
    <button><%= link_to 'Edit profile',  edit_user_registration_path %></button>
<div class="welcome-page">
    <span>Hello, <%= current_user.first_name %>!</span></ br>
    <h5><span>Do you want to make your new post?</span></h5>
    <%= link_to 'My posts', posts_path%>
    <%= link_to 'New post', new_post_path%>
    <%= link_to 'Favorite feed' %>
    <%= link_to 'My hashtags' %>
    <br>
</div>
<% else %>
    <h2>Welcome to Soft Blog. </ br>Please, log in or sign up:</h2></ br>
<div class="welcome-page">
    <%= link_to 'Log in', new_user_session_path %> or <%= link_to 'Sign up', new_user_registration_path %>
<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>%>
    <%= javascript_pack_tag 'index' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/persons/profile.html.erb
<h1>Welcome to my page!</h1>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/hashtags.html.erb
<p id="notice"><%= notice %></p>

<h1>Hashtag<%=  %></h1>
<div class="block">
<table>
  <thead>
    <tr>
      <th>Likes</th>
      <th>Title</th>
      <th>Body</th>
      <th>Image</th>
      <th colspan="3"></th>
      <th>Author</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td>
          <%= button_to like_post_path(post), method: :put do %>
              <span><%= post.get_upvotes.size %></span>
          <% end %>
        </td>
        <td><%= post.title %></td>
        <td><%= render_with_hashtags(post.body) %></td>
        <td style="width:50px; height:auto">
          <%= link_to image_tag(post.image, style:'width:100%'), posts_path %>
        </td>
        <td><button><%= link_to 'Show', post %></button></td>
        <td><button><%= link_to 'Edit', edit_post_path(post) %></button></td>
        <td><%= button_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= post.user.first_name %> <%= post.user.last_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Post', new_post_path %>
<%= link_to 'Back to my profile', user_root_path %>

</ div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>
<div class="block">
<table>
  <thead>
    <tr>
      <th>Likes</th>
      <th>Title</th>
      <th>Body</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% current_user.posts.each do |post| %>
      <tr>
        <td>
          <%= button_to like_post_path(post), method: :put do %>
              <span><%= post.get_upvotes.size %></span>
          <% end %>
        </td>
        <td><%= post.title %></td>
        <td><%= render_with_hashtags(post.body) %></td>
        <td style="width:50px; height:auto">
          <%= link_to image_tag(post.image, style:'width:100%'), posts_path %>
        </td>
        <td><button><%= link_to 'Show', post %></button></td>
        <td><button><%= link_to 'Edit', edit_post_path(post) %></button></td>
        <td><%= button_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Post', new_post_path %>
<%= link_to 'Back to my profile', user_root_path %>

</ div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<div class="block">
<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="block">
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>
<div style="width:350px; height:auto">
  <%= link_to image_tag(@post.image, style:'width:100%'), posts_path %>
</div>

<%= link_to 'Edit', edit_post_path(@post) %>
<%= link_to 'Back', posts_path %>
</div>